apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
commonLabels:         
  rhtap/gitops: hms142itd-go 
  janus-idp.io/tekton: hms142itd-go
  backstage.io/kubernetes-id: hms142itd-go
  backstage.io/kubernetes-namespace: rhtap-app 
  app.kubernetes.io/part-of: hms142itd-go
resources: 
- application-dev.yaml 
- application-stage.yaml 
- application-prod.yaml  